import type { ArchitectureProject } from './types'
import { SCHEMA_VERSION } from './schema'

export const sampleProject: ArchitectureProject = {
  schemaVersion: SCHEMA_VERSION,
  meta: {
    name: 'Auth architecture sample',
    description: 'Registration and login flows with code structure and execution logic.',
    entryFileName: 'src/modules/auth/auth.flow.ts',
    owner: 'MegaConstructor',
  },
  folders: [
    { id: 'folder-src', name: 'src', parentFolderId: null },
    { id: 'folder-modules', name: 'modules', parentFolderId: 'folder-src' },
    { id: 'folder-auth', name: 'auth', parentFolderId: 'folder-modules' },
    { id: 'folder-data', name: 'data', parentFolderId: 'folder-src' },
    { id: 'folder-integrations', name: 'integrations', parentFolderId: 'folder-src' },
  ],
  files: [
    { id: 'file-flow', name: 'auth.flow.ts', folderId: 'folder-auth', description: 'Main executable auth scenario file.' },
    { id: 'file-service', name: 'auth.service.ts', folderId: 'folder-auth', description: 'Auth orchestration service.' },
    { id: 'file-validator', name: 'auth.validator.ts', folderId: 'folder-auth', description: 'Auth validation rules.' },
    { id: 'file-repo', name: 'user.repository.ts', folderId: 'folder-data', description: 'Persistence layer for users.' },
    { id: 'file-api', name: 'notification.api.ts', folderId: 'folder-integrations', description: 'External notification gateway.' },
  ],
  classes: [
    {
      id: 'class-auth-flow',
      fileId: 'file-flow',
      name: 'AuthFlow',
      type: 'controller',
      description: 'Entry orchestration for auth scenarios.',
      dependencyIds: ['class-auth-service', 'class-auth-validator'],
    },
    {
      id: 'class-auth-service',
      fileId: 'file-service',
      name: 'AuthService',
      type: 'service',
      description: 'Business logic for registration and login.',
      dependencyIds: ['class-user-repo', 'class-notification-api'],
    },
    {
      id: 'class-auth-validator',
      fileId: 'file-validator',
      name: 'AuthValidator',
      type: 'validator',
      description: 'Validation of auth payloads.',
      dependencyIds: [],
    },
    {
      id: 'class-user-repo',
      fileId: 'file-repo',
      name: 'UserRepository',
      type: 'repository',
      description: 'User persistence access.',
      dependencyIds: [],
    },
    {
      id: 'class-notification-api',
      fileId: 'file-api',
      name: 'NotificationApi',
      type: 'utility',
      description: 'Outgoing notification integration.',
      dependencyIds: [],
    },
  ],
  methods: [
    {
      id: 'method-register-user',
      classId: 'class-auth-service',
      name: 'registerUser',
      description: 'Creates user, logs progress and sends welcome notice.',
      visibility: 'public',
      inputTypeId: 'type-registration-request',
      outputTypeId: 'type-auth-success-response',
      steps: [
        {
          id: 'method-register-loop',
          type: 'loop',
          title: 'Loop through role candidates',
          description: 'Iterate over requested roles before persistence.',
          inputRef: 'request.roles',
          outputRef: 'resolvedRoles',
          mode: 'forEach',
          collectionRef: 'request.roles',
          itemName: 'role',
          steps: [
            {
              id: 'method-register-role-check',
              type: 'conditional',
              title: 'Check legal entity role',
              description: 'Apply extra processing for legal entities.',
              inputRef: 'role',
              outputRef: 'resolvedRoles',
              condition: { left: 'role.type', operator: '==', right: 'legal_entity' },
              trueBranch: [
                {
                  id: 'method-register-log-legal',
                  type: 'log',
                  title: 'Log legal entity handling',
                  description: 'Record a legal entity path in logs.',
                  inputRef: 'role',
                  outputRef: '',
                  level: 'info',
                  message: 'Processing legal entity registration role.',
                },
              ],
              falseBranch: [],
            },
          ],
        },
        {
          id: 'method-register-save',
          type: 'save_to_db',
          title: 'Persist user',
          description: 'Save validated user in database.',
          inputRef: 'request',
          outputRef: 'savedUser',
          databaseId: 'db-main',
          tableId: 'table-users',
          operation: 'insert',
        },
        {
          id: 'method-register-notify',
          type: 'call_api',
          title: 'Send welcome notification',
          description: 'Call outbound notification API.',
          inputRef: 'savedUser',
          outputRef: 'notificationStatus',
          apiId: 'api-notification',
          endpointId: 'endpoint-send-welcome',
        },
        {
          id: 'method-register-return',
          type: 'return_result',
          title: 'Return registration result',
          description: 'Expose auth success payload.',
          inputRef: 'savedUser',
          outputRef: 'authSuccess',
          resultRef: 'authSuccess',
        },
      ],
    },
    {
      id: 'method-login-user',
      classId: 'class-auth-service',
      name: 'loginUser',
      description: 'Verifies credentials and issues a session result.',
      visibility: 'public',
      inputTypeId: 'type-login-request',
      outputTypeId: 'type-auth-success-response',
      steps: [
        {
          id: 'method-login-check-password',
          type: 'manual_action',
          title: 'Compare password hash',
          description: 'Manual comparison handled inside service.',
          inputRef: 'request.password',
          outputRef: 'passwordMatches',
          instruction: 'Compare incoming password with stored hash.',
        },
        {
          id: 'method-login-conditional',
          type: 'conditional',
          title: 'Password matches?',
          description: 'Choose success or failure branch.',
          inputRef: 'passwordMatches',
          outputRef: 'loginOutcome',
          condition: { left: 'passwordMatches', operator: '==', right: 'true' },
          trueBranch: [
            {
              id: 'method-login-log-success',
              type: 'log',
              title: 'Log success',
              description: 'Record successful authentication.',
              inputRef: 'user',
              outputRef: '',
              level: 'info',
              message: 'User successfully authenticated.',
            },
          ],
          falseBranch: [
            {
              id: 'method-login-error',
              type: 'throw_error',
              title: 'Reject credentials',
              description: 'Stop flow for invalid credentials.',
              inputRef: 'request',
              outputRef: 'AuthError',
              errorCode: 'INVALID_CREDENTIALS',
              message: 'Invalid login or password.',
            },
          ],
        },
        {
          id: 'method-login-return',
          type: 'return_result',
          title: 'Return login result',
          description: 'Return success response.',
          inputRef: 'user',
          outputRef: 'authSuccess',
          resultRef: 'authSuccess',
        },
      ],
    },
    {
      id: 'method-validate-registration',
      classId: 'class-auth-validator',
      name: 'validateRegistrationPayload',
      description: 'Validates registration request structure.',
      visibility: 'public',
      inputTypeId: 'type-registration-request',
      outputTypeId: 'type-validation-result',
      steps: [
        {
          id: 'method-validator-input',
          type: 'receive_input',
          title: 'Read request',
          description: 'Receive incoming payload.',
          inputRef: 'request',
          outputRef: 'request',
        },
        {
          id: 'method-validator-check-email',
          type: 'validate',
          title: 'Check email format',
          description: 'Ensure email format is valid.',
          inputRef: 'request.email',
          outputRef: 'emailValidated',
          rule: 'email must be valid',
        },
        {
          id: 'method-validator-return',
          type: 'return_result',
          title: 'Return validation result',
          description: 'Return validation status.',
          inputRef: 'emailValidated',
          outputRef: 'validationResult',
          resultRef: 'validationResult',
        },
      ],
    },
    {
      id: 'method-save-user',
      classId: 'class-user-repo',
      name: 'saveUser',
      description: 'Repository insert into users table.',
      visibility: 'public',
      inputTypeId: 'type-registration-request',
      outputTypeId: 'type-user-record',
      steps: [
        {
          id: 'method-save-db',
          type: 'save_to_db',
          title: 'Insert into users',
          description: 'Insert user record.',
          inputRef: 'request',
          outputRef: 'savedUser',
          databaseId: 'db-main',
          tableId: 'table-users',
          operation: 'insert',
        },
      ],
    },
  ],
  dataStructures: [
    {
      id: 'type-registration-request',
      name: 'RegistrationRequest',
      kind: 'object',
      description: 'Payload for registration trigger.',
      fields: [
        { id: 'field-reg-email', name: 'email', type: 'string', required: true, description: 'User email', source: 'client', example: 'user@example.com' },
        { id: 'field-reg-password', name: 'password', type: 'string', required: true, description: 'User password', source: 'client', example: 'secret' },
        { id: 'field-reg-roles', name: 'roles', type: 'RoleItem[]', required: false, description: 'Requested roles', source: 'client', example: '[{"type":"legal_entity"}]' },
      ],
    },
    {
      id: 'type-login-request',
      name: 'LoginRequest',
      kind: 'object',
      description: 'Payload for login trigger.',
      fields: [
        { id: 'field-login-email', name: 'email', type: 'string', required: true, description: 'User email', source: 'client', example: 'user@example.com' },
        { id: 'field-login-password', name: 'password', type: 'string', required: true, description: 'User password', source: 'client', example: 'secret' },
      ],
    },
    {
      id: 'type-auth-success-response',
      name: 'AuthSuccessResponse',
      kind: 'object',
      description: 'Standard auth success payload.',
      fields: [
        { id: 'field-auth-token', name: 'token', type: 'string', required: true, description: 'Issued token', source: 'system', example: 'jwt-token' },
        { id: 'field-auth-user-id', name: 'userId', type: 'string', required: true, description: 'Current user id', source: 'system', example: 'usr_123' },
      ],
    },
    {
      id: 'type-validation-result',
      name: 'ValidationResult',
      kind: 'object',
      description: 'Validation outcome.',
      fields: [
        { id: 'field-valid-ok', name: 'isValid', type: 'boolean', required: true, description: 'Validation state', source: 'system', example: 'true' },
      ],
    },
    {
      id: 'type-user-record',
      name: 'UserRecord',
      kind: 'object',
      description: 'Persisted user row.',
      fields: [
        { id: 'field-user-id', name: 'id', type: 'string', required: true, description: 'User id', source: 'database', example: 'usr_123' },
        { id: 'field-user-email', name: 'email', type: 'string', required: true, description: 'Stored email', source: 'database', example: 'user@example.com' },
      ],
    },
  ],
  scenarios: [
    {
      id: 'scenario-registration',
      name: 'Registration',
      description: 'Registration request from trigger to response.',
      trigger: {
        id: 'trigger-registration',
        name: 'Registration request',
        type: 'http_request',
        description: 'Client sends registration form data.',
      },
      requestTypeId: 'type-registration-request',
      responseTypeId: 'type-auth-success-response',
      usedClassIds: ['class-auth-validator', 'class-auth-service'],
      usedMethodIds: ['method-validate-registration', 'method-register-user'],
      usedDatabaseIds: ['db-main'],
      usedApiIds: ['api-notification'],
      steps: [
        {
          id: 'scenario-registration-input',
          type: 'receive_input',
          title: 'Receive registration payload',
          description: 'Collect only required request data.',
          inputRef: 'client.body',
          outputRef: 'request',
        },
        {
          id: 'scenario-registration-validate',
          type: 'call_method',
          title: 'Validate registration',
          description: 'Invoke validator method from logic flow.',
          inputRef: 'request',
          outputRef: 'validationResult',
          classId: 'class-auth-validator',
          methodId: 'method-validate-registration',
        },
        {
          id: 'scenario-registration-conditional',
          type: 'conditional',
          title: 'Validation succeeded?',
          description: 'Stop flow when validation fails.',
          inputRef: 'validationResult',
          outputRef: 'registrationOutcome',
          condition: { left: 'validationResult.isValid', operator: '==', right: 'true' },
          trueBranch: [
            {
              id: 'scenario-registration-call-service',
              type: 'call_method',
              title: 'Run registration service',
              description: 'Execute service orchestration.',
              inputRef: 'request',
              outputRef: 'authSuccess',
              classId: 'class-auth-service',
              methodId: 'method-register-user',
            },
            {
              id: 'scenario-registration-build-response',
              type: 'build_response',
              title: 'Build success response',
              description: 'Prepare client response payload.',
              inputRef: 'authSuccess',
              outputRef: 'response',
              responseTypeId: 'type-auth-success-response',
            },
          ],
          falseBranch: [
            {
              id: 'scenario-registration-error',
              type: 'throw_error',
              title: 'Validation error',
              description: 'Return validation error to client.',
              inputRef: 'validationResult',
              outputRef: 'ValidationError',
              errorCode: 'VALIDATION_ERROR',
              message: 'Registration payload is invalid.',
            },
          ],
        },
        {
          id: 'scenario-registration-return',
          type: 'return_result',
          title: 'Return response',
          description: 'Send result to client.',
          inputRef: 'response',
          outputRef: 'client.response',
          resultRef: 'client.response',
        },
      ],
    },
    {
      id: 'scenario-login',
      name: 'Login',
      description: 'Login request from input to result.',
      trigger: {
        id: 'trigger-login',
        name: 'Login request',
        type: 'http_request',
        description: 'Client sends login credentials.',
      },
      requestTypeId: 'type-login-request',
      responseTypeId: 'type-auth-success-response',
      usedClassIds: ['class-auth-service'],
      usedMethodIds: ['method-login-user'],
      usedDatabaseIds: [],
      usedApiIds: [],
      steps: [
        {
          id: 'scenario-login-input',
          type: 'receive_input',
          title: 'Receive login payload',
          description: 'Read client login request.',
          inputRef: 'client.body',
          outputRef: 'request',
        },
        {
          id: 'scenario-login-service',
          type: 'call_method',
          title: 'Run login service',
          description: 'Execute login business method.',
          inputRef: 'request',
          outputRef: 'authSuccess',
          classId: 'class-auth-service',
          methodId: 'method-login-user',
        },
        {
          id: 'scenario-login-build-response',
          type: 'build_response',
          title: 'Build login response',
          description: 'Prepare auth success response.',
          inputRef: 'authSuccess',
          outputRef: 'response',
          responseTypeId: 'type-auth-success-response',
        },
        {
          id: 'scenario-login-return',
          type: 'return_result',
          title: 'Return login result',
          description: 'Send auth response to client.',
          inputRef: 'response',
          outputRef: 'client.response',
          resultRef: 'client.response',
        },
      ],
    },
  ],
  databases: [
    {
      id: 'db-main',
      name: 'MainDb',
      type: 'postgresql',
      description: 'Primary storage for users and sessions.',
      tables: [
        {
          id: 'table-users',
          name: 'users',
          description: 'Registered users.',
          fields: ['id', 'email', 'password_hash', 'created_at'],
        },
      ],
    },
  ],
  apis: [
    {
      id: 'api-notification',
      name: 'Notification API',
      baseUrl: 'https://notify.internal',
      description: 'External API for user messages.',
      endpoints: [
        {
          id: 'endpoint-send-welcome',
          name: 'SendWelcomeEmail',
          method: 'POST',
          path: '/welcome',
          description: 'Send welcome email after registration.',
          requestTypeId: 'type-user-record',
          responseTypeId: 'type-validation-result',
        },
      ],
    },
  ],
}
