import type { ArchitectureProject } from './types'
import { SCHEMA_VERSION } from './schema'

export const sampleProject: ArchitectureProject = {
  schemaVersion: SCHEMA_VERSION,
  meta: {
    name: 'WordPress Telegram Post Notifier',
    description: 'Blueprint of a WordPress plugin where file layout and Telegram notification flow are modeled as separate but related layers.',
    entryFileName: 'wp-telegram-post-notifier/wp-telegram-post-notifier.php',
    owner: 'RealPosterumAdmin',
  },
  folders: [
    { id: 'folder-plugin-root', name: 'wp-telegram-post-notifier', parentFolderId: null },
    { id: 'folder-includes', name: 'includes', parentFolderId: 'folder-plugin-root' },
  ],
  files: [
    {
      id: 'file-plugin-main',
      name: 'wp-telegram-post-notifier.php',
      folderId: 'folder-plugin-root',
      description: 'Main plugin file recognized by WordPress. It represents physical placement only and does not own the full business scenario.',
    },
    {
      id: 'file-plugin-includes',
      name: 'telegram-post-functions.php',
      folderId: 'folder-includes',
      description: 'Physical helper file under includes. Reusable behavior is modeled through class methods instead of binding scenarios one-to-one to files.',
    },
  ],
  classes: [
    {
      id: 'class-plugin-bootstrap',
      fileId: 'file-plugin-main',
      name: 'TelegramPostNotifierPlugin',
      type: 'controller',
      description: 'Registers the WordPress hook and delegates post publication events to the helper/service layer.',
      dependencyIds: ['class-telegram-helper'],
    },
    {
      id: 'class-telegram-helper',
      fileId: 'file-plugin-includes',
      name: 'TelegramPostFunctions',
      type: 'utility',
      description: 'Utility/service class used as the reusable behavior container for the plugin blueprint, even if real PHP would use plain functions.',
      dependencyIds: [],
    },
  ],
  methods: [
    {
      id: 'method-collect-post-data',
      classId: 'class-telegram-helper',
      name: 'collectPostData',
      description: 'Reads the WordPress hook payload and normalizes the post fields used in the notification flow.',
      visibility: 'private',
      inputTypeId: 'type-wp-post-payload',
      outputTypeId: 'type-wp-post-payload',
      steps: [
        {
          id: 'method-collect-post-input',
          type: 'receive_input',
          title: 'Receive hook payload',
          description: 'Read the post object passed by the WordPress hook.',
          inputRef: 'wp.hook.post',
          outputRef: 'rawPost',
        },
        {
          id: 'method-collect-post-map',
          type: 'map_data',
          title: 'Normalize post fields',
          description: 'Keep only the fields needed by the Telegram notification blueprint.',
          inputRef: 'rawPost',
          outputRef: 'postPayload',
          mapping: 'Map postId, postType, postStatus, title, permalink and authorDisplayName into WpPostPayload.',
        },
        {
          id: 'method-collect-post-return',
          type: 'return_result',
          title: 'Return normalized post',
          description: 'Expose the normalized WordPress payload for the next steps.',
          inputRef: 'postPayload',
          outputRef: 'postPayload',
          resultRef: 'postPayload',
        },
      ],
    },
    {
      id: 'method-check-post-eligibility',
      classId: 'class-telegram-helper',
      name: 'checkPostEligibility',
      description: 'Decides whether the current WordPress post event should trigger a Telegram notification.',
      visibility: 'private',
      inputTypeId: 'type-wp-post-payload',
      steps: [
        {
          id: 'method-check-post-input',
          type: 'receive_input',
          title: 'Read normalized post',
          description: 'Accept the normalized post payload from the scenario.',
          inputRef: 'postPayload',
          outputRef: 'postPayload',
        },
        {
          id: 'method-check-post-status',
          type: 'validate',
          title: 'Check publish status',
          description: 'Verify that the hook represents post creation or publication.',
          inputRef: 'postPayload.postStatus',
          outputRef: 'statusCheck',
          rule: 'post status should be publish',
        },
        {
          id: 'method-check-post-type',
          type: 'validate',
          title: 'Check post type',
          description: 'Make sure the event belongs to the target WordPress post type.',
          inputRef: 'postPayload.postType',
          outputRef: 'typeCheck',
          rule: 'post type should be post',
        },
        {
          id: 'method-check-post-return',
          type: 'return_result',
          title: 'Return post decision',
          description: 'Expose the decision object used by the scenario branch.',
          inputRef: 'postPayload',
          outputRef: 'postDecision',
          resultRef: 'postDecision',
        },
      ],
    },
    {
      id: 'method-build-telegram-message',
      classId: 'class-telegram-helper',
      name: 'buildTelegramMessage',
      description: 'Builds the Telegram message text from the WordPress post payload.',
      visibility: 'private',
      inputTypeId: 'type-wp-post-payload',
      outputTypeId: 'type-telegram-message-payload',
      steps: [
        {
          id: 'method-build-message-input',
          type: 'receive_input',
          title: 'Receive post payload',
          description: 'Read the post data prepared for notification.',
          inputRef: 'postPayload',
          outputRef: 'postPayload',
        },
        {
          id: 'method-build-message-map',
          type: 'map_data',
          title: 'Compose Telegram text',
          description: 'Prepare the outgoing Telegram message body.',
          inputRef: 'postPayload',
          outputRef: 'telegramMessage',
          mapping: 'Fill chatId from PluginSettings and build text from post title, permalink and authorDisplayName.',
        },
        {
          id: 'method-build-message-return',
          type: 'return_result',
          title: 'Return message payload',
          description: 'Expose the Telegram message payload for delivery.',
          inputRef: 'telegramMessage',
          outputRef: 'telegramMessage',
          resultRef: 'telegramMessage',
        },
      ],
    },
    {
      id: 'method-send-telegram-request',
      classId: 'class-telegram-helper',
      name: 'sendTelegramRequest',
      description: 'Sends the prepared message to Telegram Bot API and routes failures through a dedicated error handler.',
      visibility: 'private',
      inputTypeId: 'type-telegram-message-payload',
      outputTypeId: 'type-telegram-api-response',
      steps: [
        {
          id: 'method-send-telegram-input',
          type: 'receive_input',
          title: 'Receive message payload',
          description: 'Read the prepared Telegram payload.',
          inputRef: 'telegramMessage',
          outputRef: 'telegramMessage',
        },
        {
          id: 'method-send-telegram-settings',
          type: 'manual_action',
          title: 'Read plugin settings',
          description: 'Load WordPress plugin settings required for the Telegram request.',
          inputRef: 'wordpress.options',
          outputRef: 'pluginSettings',
          instruction: 'Read PluginSettings with botToken and chatId before the API call.',
        },
        {
          id: 'method-send-telegram-map',
          type: 'map_data',
          title: 'Finalize Telegram request',
          description: 'Combine the message body with plugin settings before calling Telegram.',
          inputRef: 'telegramMessage + pluginSettings',
          outputRef: 'telegramRequest',
          mapping: 'Use botToken from PluginSettings for API auth and ensure chatId is populated in TelegramMessagePayload.',
        },
        {
          id: 'method-send-telegram-api',
          type: 'call_api',
          title: 'Call Telegram sendMessage',
          description: 'Send the message through Telegram Bot API.',
          inputRef: 'telegramRequest',
          outputRef: 'telegramResponse',
          apiId: 'api-telegram-bot',
          endpointId: 'endpoint-telegram-send-message',
        },
        {
          id: 'method-send-telegram-conditional',
          type: 'conditional',
          title: 'Telegram accepted request?',
          description: 'Return success or route failure to the reusable error handler.',
          inputRef: 'telegramResponse',
          outputRef: 'telegramOutcome',
          condition: { left: 'telegramResponse.ok', operator: '==', right: 'true' },
          trueBranch: [
            {
              id: 'method-send-telegram-return',
              type: 'return_result',
              title: 'Return Telegram response',
              description: 'Expose the successful Telegram API response.',
              inputRef: 'telegramResponse',
              outputRef: 'telegramResponse',
              resultRef: 'telegramResponse',
            },
          ],
          falseBranch: [
            {
              id: 'method-send-telegram-error-handler',
              type: 'call_method',
              title: 'Handle Telegram error',
              description: 'Run the reusable error handling method before failing the flow.',
              inputRef: 'telegramResponse',
              outputRef: 'telegramError',
              classId: 'class-telegram-helper',
              methodId: 'method-handle-send-error',
            },
            {
              id: 'method-send-telegram-throw',
              type: 'throw_error',
              title: 'Stop on Telegram failure',
              description: 'Stop the method when Telegram rejects the request.',
              inputRef: 'telegramError',
              outputRef: 'TelegramSendError',
              errorCode: 'TELEGRAM_SEND_FAILED',
              message: 'Telegram Bot API did not accept the sendMessage request.',
            },
          ],
        },
      ],
    },
    {
      id: 'method-handle-send-error',
      classId: 'class-telegram-helper',
      name: 'handleSendError',
      description: 'Collects delivery failure context so the scenario keeps a dedicated error-handling step in the blueprint.',
      visibility: 'private',
      inputTypeId: 'type-telegram-api-response',
      outputTypeId: 'type-telegram-api-response',
      steps: [
        {
          id: 'method-handle-error-input',
          type: 'receive_input',
          title: 'Receive failed response',
          description: 'Accept the failed Telegram API response.',
          inputRef: 'telegramResponse',
          outputRef: 'telegramResponse',
        },
        {
          id: 'method-handle-error-log',
          type: 'log',
          title: 'Log Telegram failure',
          description: 'Capture the failure reason for operators.',
          inputRef: 'telegramResponse.description',
          outputRef: '',
          level: 'error',
          message: 'Telegram delivery failed for the current WordPress post notification.',
        },
        {
          id: 'method-handle-error-return',
          type: 'return_result',
          title: 'Return error context',
          description: 'Expose the failed response for the caller.',
          inputRef: 'telegramResponse',
          outputRef: 'telegramError',
          resultRef: 'telegramError',
        },
      ],
    },
  ],
  dataStructures: [
    {
      id: 'type-wp-post-payload',
      name: 'WpPostPayload',
      kind: 'object',
      description: 'Normalized WordPress post event data used by the notification scenario.',
      fields: [
        { id: 'field-post-id', name: 'postId', type: 'number', required: true, description: 'WordPress post identifier.', source: 'wordpress_hook', example: '42' },
        { id: 'field-post-type', name: 'postType', type: 'string', required: true, description: 'Post type, such as post or page.', source: 'wordpress_hook', example: 'post' },
        { id: 'field-post-status', name: 'postStatus', type: 'string', required: true, description: 'Current WordPress post status.', source: 'wordpress_hook', example: 'publish' },
        { id: 'field-post-title', name: 'title', type: 'string', required: true, description: 'Published post title.', source: 'wordpress_hook', example: 'New release notes' },
        { id: 'field-post-permalink', name: 'permalink', type: 'string', required: true, description: 'Permalink of the published post.', source: 'wordpress_hook', example: 'https://example.com/new-release-notes' },
        { id: 'field-post-author', name: 'authorDisplayName', type: 'string', required: false, description: 'Display name of the post author.', source: 'wordpress_hook', example: 'Site Editor' },
      ],
    },
    {
      id: 'type-telegram-message-payload',
      name: 'TelegramMessagePayload',
      kind: 'object',
      description: 'Request body prepared for Telegram Bot API sendMessage endpoint.',
      fields: [
        { id: 'field-telegram-chat-id', name: 'chatId', type: 'string', required: true, description: 'Destination Telegram chat identifier.', source: 'plugin_settings', example: '-1001234567890' },
        { id: 'field-telegram-text', name: 'text', type: 'string', required: true, description: 'Rendered Telegram message text.', source: 'system', example: 'New post published: New release notes https://example.com/new-release-notes' },
        { id: 'field-telegram-parse-mode', name: 'parseMode', type: 'string', required: false, description: 'Optional Telegram parse mode.', source: 'system', example: 'HTML' },
      ],
    },
    {
      id: 'type-telegram-api-response',
      name: 'TelegramApiResponse',
      kind: 'object',
      description: 'Simplified response returned by Telegram Bot API after sendMessage.',
      fields: [
        { id: 'field-api-ok', name: 'ok', type: 'boolean', required: true, description: 'Whether Telegram accepted the request.', source: 'telegram_api', example: 'true' },
        { id: 'field-api-message-id', name: 'messageId', type: 'number', required: false, description: 'Identifier of the created Telegram message.', source: 'telegram_api', example: '915' },
        { id: 'field-api-description', name: 'description', type: 'string', required: false, description: 'Telegram API diagnostic message.', source: 'telegram_api', example: 'Bad Request: chat not found' },
      ],
    },
    {
      id: 'type-plugin-settings',
      name: 'PluginSettings',
      kind: 'object',
      description: 'Stored WordPress plugin settings required for Telegram delivery.',
      fields: [
        { id: 'field-settings-bot-token', name: 'botToken', type: 'string', required: true, description: 'Telegram bot token configured in plugin settings.', source: 'wordpress_options', example: '123456:ABC-DEF' },
        { id: 'field-settings-chat-id', name: 'chatId', type: 'string', required: true, description: 'Default Telegram chat id configured in plugin settings.', source: 'wordpress_options', example: '-1001234567890' },
      ],
    },
  ],
  scenarios: [
    {
      id: 'scenario-wordpress-post-to-telegram',
      name: 'Send Telegram notification on post publish',
      description: 'Logical business chain for the WordPress plugin. Files describe physical placement, while this scenario describes the post-to-Telegram flow.',
      trigger: {
        id: 'trigger-wordpress-post-publish',
        name: 'WordPress post create or publish hook',
        type: 'wordpress_hook',
        description: 'A WordPress hook fires when a post is created or published.',
      },
      requestTypeId: 'type-wp-post-payload',
      responseTypeId: 'type-telegram-api-response',
      usedClassIds: ['class-plugin-bootstrap', 'class-telegram-helper'],
      usedMethodIds: [
        'method-collect-post-data',
        'method-check-post-eligibility',
        'method-build-telegram-message',
        'method-send-telegram-request',
        'method-handle-send-error',
      ],
      usedDatabaseIds: [],
      usedApiIds: ['api-telegram-bot'],
      steps: [
        {
          id: 'scenario-post-input',
          type: 'receive_input',
          title: 'Receive WordPress post event',
          description: 'Accept the WordPress hook payload when a post is created or published.',
          inputRef: 'wp.hook.post',
          outputRef: 'hookPost',
        },
        {
          id: 'scenario-post-collect',
          type: 'call_method',
          title: 'Collect post data',
          description: 'Normalize the WordPress post data for the blueprint.',
          inputRef: 'hookPost',
          outputRef: 'postPayload',
          classId: 'class-telegram-helper',
          methodId: 'method-collect-post-data',
        },
        {
          id: 'scenario-post-check',
          type: 'call_method',
          title: 'Check event relevance',
          description: 'Verify that the event should trigger Telegram delivery.',
          inputRef: 'postPayload',
          outputRef: 'postDecision',
          classId: 'class-telegram-helper',
          methodId: 'method-check-post-eligibility',
        },
        {
          id: 'scenario-post-conditional',
          type: 'conditional',
          title: 'Post should be sent?',
          description: 'Branch between Telegram delivery and an explicit skipped result.',
          inputRef: 'postDecision',
          outputRef: 'scenarioOutcome',
          condition: { left: 'postDecision.shouldSend', operator: '==', right: 'true' },
          trueBranch: [
            {
              id: 'scenario-post-build-message',
              type: 'call_method',
              title: 'Prepare Telegram message',
              description: 'Build the Telegram message payload from the post data.',
              inputRef: 'postPayload',
              outputRef: 'telegramMessage',
              classId: 'class-telegram-helper',
              methodId: 'method-build-telegram-message',
            },
            {
              id: 'scenario-post-send-message',
              type: 'call_method',
              title: 'Send to Telegram Bot API',
              description: 'Deliver the message through the reusable Telegram request method.',
              inputRef: 'telegramMessage',
              outputRef: 'telegramResponse',
              classId: 'class-telegram-helper',
              methodId: 'method-send-telegram-request',
            },
          ],
          falseBranch: [
            {
              id: 'scenario-post-skip-map',
              type: 'map_data',
              title: 'Build skipped result',
              description: 'Return an explicit result for unsupported post events instead of silently doing nothing.',
              inputRef: 'postDecision',
              outputRef: 'telegramResponse',
              mapping: 'Set ok=false, messageId=0 and description="WordPress event skipped by plugin rules".',
            },
          ],
        },
        {
          id: 'scenario-post-return',
          type: 'return_result',
          title: 'Finish scenario',
          description: 'Return the final scenario result after send or skip.',
          inputRef: 'telegramResponse',
          outputRef: 'scenario.result',
          resultRef: 'scenario.result',
        },
      ],
    },
  ],
  databases: [],
  apis: [
    {
      id: 'api-telegram-bot',
      name: 'Telegram Bot API',
      baseUrl: 'https://api.telegram.org',
      description: 'External Telegram HTTP API used by the plugin blueprint.',
      endpoints: [
        {
          id: 'endpoint-telegram-send-message',
          name: 'sendMessage',
          method: 'POST',
          path: '/bot{botToken}/sendMessage',
          description: 'Send a Telegram notification when WordPress publishes a post.',
          requestTypeId: 'type-telegram-message-payload',
          responseTypeId: 'type-telegram-api-response',
        },
      ],
    },
  ],
}
